//! Deepgram WebSocket response types.
//!
//! These types model the JSON responses returned by the Deepgram streaming
//! transcription API over WebSocket.

use serde::Deserialize;

/// Top-level response from Deepgram's streaming WebSocket API.
#[derive(Debug, Deserialize)]
pub struct DeepgramResponse {
    /// The type of response: `"Results"`, `"SpeechStarted"`, `"UtteranceEnd"`, etc.
    #[serde(rename = "type")]
    pub response_type: Option<String>,

    /// Channel containing transcription alternatives.
    pub channel: Option<Channel>,

    /// Whether this is a final transcription result (not interim).
    pub is_final: Option<bool>,

    /// Whether this marks the end of a speech segment.
    pub speech_final: Option<bool>,

    /// Whether this result was generated by a finalize request.
    pub from_finalize: Option<bool>,

    /// Index information for the channel.
    pub channel_index: Option<Vec<u32>>,

    /// Duration of the audio segment in seconds.
    pub duration: Option<f64>,

    /// Start time of the audio segment in seconds.
    pub start: Option<f64>,
}

/// A single channel in a Deepgram response.
#[derive(Debug, Deserialize)]
pub struct Channel {
    /// Transcription alternatives, ordered by confidence (highest first).
    pub alternatives: Vec<Alternative>,
}

/// A single transcription alternative.
#[derive(Debug, Deserialize)]
pub struct Alternative {
    /// The transcribed text.
    pub transcript: String,

    /// Confidence score (0.0 to 1.0).
    pub confidence: f64,

    /// Word-level details (may be empty).
    #[serde(default)]
    pub words: Vec<Word>,
}

/// Word-level timing and confidence information.
#[derive(Debug, Deserialize)]
pub struct Word {
    /// The word text.
    pub word: String,

    /// Start time in seconds.
    pub start: f64,

    /// End time in seconds.
    pub end: f64,

    /// Confidence score for this word.
    pub confidence: f64,
}

impl DeepgramResponse {
    /// Extract the best transcript from the response.
    ///
    /// Returns `None` if no channel or alternatives are present, or if the
    /// transcript is empty.
    pub fn transcript(&self) -> Option<&str> {
        self.channel
            .as_ref()
            .and_then(|c| c.alternatives.first())
            .map(|a| a.transcript.as_str())
            .filter(|t| !t.is_empty())
    }

    /// The confidence of the best alternative, or 0.0 if unavailable.
    pub fn confidence(&self) -> f64 {
        self.channel
            .as_ref()
            .and_then(|c| c.alternatives.first())
            .map(|a| a.confidence)
            .unwrap_or(0.0)
    }

    /// Whether this is a final (non-interim) result.
    pub fn is_final(&self) -> bool {
        self.is_final.unwrap_or(false)
    }

    /// Whether this marks the end of a speech segment.
    pub fn is_speech_final(&self) -> bool {
        self.speech_final.unwrap_or(false)
    }

    /// Whether this is a "Results" type response.
    pub fn is_results(&self) -> bool {
        self.response_type.as_deref() == Some("Results")
    }

    /// Whether this is a "SpeechStarted" event.
    pub fn is_speech_started(&self) -> bool {
        self.response_type.as_deref() == Some("SpeechStarted")
    }

    /// Whether this is an "UtteranceEnd" event.
    pub fn is_utterance_end(&self) -> bool {
        self.response_type.as_deref() == Some("UtteranceEnd")
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const FINAL_RESPONSE_JSON: &str = r#"{
        "type": "Results",
        "channel_index": [0, 1],
        "duration": 1.54,
        "start": 0.0,
        "is_final": true,
        "speech_final": true,
        "channel": {
            "alternatives": [
                {
                    "transcript": "hello world",
                    "confidence": 0.99,
                    "words": [
                        {"word": "hello", "start": 0.0, "end": 0.5, "confidence": 0.98},
                        {"word": "world", "start": 0.6, "end": 1.0, "confidence": 0.99}
                    ]
                }
            ]
        }
    }"#;

    const INTERIM_RESPONSE_JSON: &str = r#"{
        "type": "Results",
        "channel_index": [0, 1],
        "duration": 0.8,
        "start": 0.0,
        "is_final": false,
        "speech_final": false,
        "channel": {
            "alternatives": [
                {
                    "transcript": "hel",
                    "confidence": 0.75,
                    "words": []
                }
            ]
        }
    }"#;

    const EMPTY_TRANSCRIPT_JSON: &str = r#"{
        "type": "Results",
        "channel_index": [0, 1],
        "duration": 0.5,
        "start": 0.0,
        "is_final": true,
        "speech_final": false,
        "channel": {
            "alternatives": [
                {
                    "transcript": "",
                    "confidence": 0.0,
                    "words": []
                }
            ]
        }
    }"#;

    const SPEECH_STARTED_JSON: &str = r#"{
        "type": "SpeechStarted",
        "channel_index": [0, 1],
        "duration": 0.0,
        "start": 0.0
    }"#;

    const UTTERANCE_END_JSON: &str = r#"{
        "type": "UtteranceEnd",
        "channel_index": [0, 1]
    }"#;

    #[test]
    fn parse_final_response() {
        let resp: DeepgramResponse =
            serde_json::from_str(FINAL_RESPONSE_JSON).expect("should parse");
        assert!(resp.is_results());
        assert!(resp.is_final());
        assert!(resp.is_speech_final());
        assert_eq!(resp.transcript(), Some("hello world"));
        assert!((resp.confidence() - 0.99).abs() < f64::EPSILON);
        assert_eq!(resp.duration, Some(1.54));
        assert_eq!(resp.start, Some(0.0));

        let words = &resp.channel.unwrap().alternatives[0].words;
        assert_eq!(words.len(), 2);
        assert_eq!(words[0].word, "hello");
        assert_eq!(words[1].word, "world");
    }

    #[test]
    fn parse_interim_response() {
        let resp: DeepgramResponse =
            serde_json::from_str(INTERIM_RESPONSE_JSON).expect("should parse");
        assert!(resp.is_results());
        assert!(!resp.is_final());
        assert!(!resp.is_speech_final());
        assert_eq!(resp.transcript(), Some("hel"));
        assert!((resp.confidence() - 0.75).abs() < f64::EPSILON);
    }

    #[test]
    fn parse_empty_transcript() {
        let resp: DeepgramResponse =
            serde_json::from_str(EMPTY_TRANSCRIPT_JSON).expect("should parse");
        assert!(resp.is_final());
        // Empty transcript should return None
        assert_eq!(resp.transcript(), None);
        assert!((resp.confidence() - 0.0).abs() < f64::EPSILON);
    }

    #[test]
    fn parse_speech_started() {
        let resp: DeepgramResponse =
            serde_json::from_str(SPEECH_STARTED_JSON).expect("should parse");
        assert!(resp.is_speech_started());
        assert!(!resp.is_results());
        assert!(!resp.is_final());
        assert_eq!(resp.transcript(), None);
        assert_eq!(resp.confidence(), 0.0);
    }

    #[test]
    fn parse_utterance_end() {
        let resp: DeepgramResponse =
            serde_json::from_str(UTTERANCE_END_JSON).expect("should parse");
        assert!(resp.is_utterance_end());
        assert!(!resp.is_results());
        assert_eq!(resp.transcript(), None);
    }

    #[test]
    fn parse_no_channel() {
        let json = r#"{"type": "Results", "is_final": true}"#;
        let resp: DeepgramResponse = serde_json::from_str(json).expect("should parse");
        assert_eq!(resp.transcript(), None);
        assert_eq!(resp.confidence(), 0.0);
    }

    #[test]
    fn parse_empty_alternatives() {
        let json = r#"{
            "type": "Results",
            "is_final": true,
            "channel": {"alternatives": []}
        }"#;
        let resp: DeepgramResponse = serde_json::from_str(json).expect("should parse");
        assert_eq!(resp.transcript(), None);
        assert_eq!(resp.confidence(), 0.0);
    }

    #[test]
    fn unknown_type_is_handled() {
        let json = r#"{"type": "Metadata", "request_id": "abc"}"#;
        let resp: DeepgramResponse = serde_json::from_str(json).expect("should parse");
        assert!(!resp.is_results());
        assert!(!resp.is_speech_started());
        assert!(!resp.is_utterance_end());
        assert_eq!(resp.response_type.as_deref(), Some("Metadata"));
    }

    #[test]
    fn response_is_debug() {
        let resp: DeepgramResponse =
            serde_json::from_str(FINAL_RESPONSE_JSON).expect("should parse");
        let debug = format!("{:?}", resp);
        assert!(debug.contains("DeepgramResponse"));
    }
}
